import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Kanit} from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Varity Calculator Web Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
